create table if not exists public.students (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  name text not null,
  age integer not null,
  grade double precision not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_students_owner_id on public.students (owner_id);
create index if not exists idx_students_id_owner_id on public.students (id, owner_id);
